const actionTypes = {
    GET_ALL_PROJECTS: "GET_ALL_PROJECTS",
    SET_ALL_PROJECTS: "SET_ALL_PROJECTS",
    GET_CONTACT_INFO: "GET_CONTACT_INFO",
    SET_CONTACT_INFO: "SET_CONTACT_INFO"
};

export default actionTypes;