const actionTypes = {
    GET_ALL_PROJECTS: "GET_ALL_PROJECTS",
    SET_ALL_PROJECTS: "SET_ALL_PROJECTS",
    GET_CONTACT_INFO: "GET_CONTACT_INFO",
    SET_CONTACT_INFO: "SET_CONTACT_INFO",
    SET_ABOUT_INFO: "SET_ABOUT_INFO",
    GET_ABOUT_INFO: "GET_ABOUT_INFO",
    SET_PERSONAL_INFO: "SET_PERSONAL_INFO",
    GET_PERSONAL_INFO: "GET_PERSONAL_INFO",
    SET_HOBBIES: "SET_HOBBIES",
    GET_HOBBIES: "GET_HOBBIES",
    SET_ACTIVE_FILE: "SET_ACTIVE_FILE",
    GET_ACTIVE_FILE: "GET_ACTIVE_FILE"
};

export default actionTypes;